services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - /:/srv #Change to match your directory
      - /home/nos/shared/docker/filebrowser/filebrowser.db:/database/filebrowser.db #Change to match your directory
      - /home/nos/shared/docker/filebrowser/settings.json:/config/settings.json #Change to match your directory
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
    # No need to expose ports if NPM is creating a domain name for it
    # ports:
    #   - 8080:80 #Change the port if needed

networks:
  default:
    external: true
    name: npm
