services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      # Optionally, also mount docker socket if you want to use the docker containers widget
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # No need to expose ports if NPM is creating a domain name for it
    # ports:
    #   - 8081:8080
    env_file: .env

networks:
  default:
    external: true
    name: npm