services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # No need to expose ports if NPM is creating a domain name for it
    # ports:
    #   - 8080:8080
    environment:
      #For accessing logs on another remote machine that has dozzle-agent installed and using the port mentioned
      - DOZZLE_REMOTE_AGENT=192.168.100.35:7007
      # Uncomment to enable container actions (stop, start, restart). See https://dozzle.dev/guide/actions
      # - DOZZLE_ENABLE_ACTIONS=true
      #
      # Uncomment to allow access to container shells. See https://dozzle.dev/guide/shell
      # - DOZZLE_ENABLE_SHELL=true
      #
      # Uncomment to enable authentication. See https://dozzle.dev/guide/authentication
      # - DOZZLE_AUTH_PROVIDER=simple

networks:
  default:
    external: true
    name: npm